# Generated by Django 4.0.5 on 2022-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20, verbose_name='Назва події')),
                ('event_description', models.TextField(verbose_name='Опис події')),
                ('event_date', models.DateTimeField(verbose_name='Час проведення події')),
            ],
        ),
    ]
